name: CI/CD Pipeline

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff dvc-gdrive

        # 4. Configure DVC Google Drive authentication
      - name: Configure DVC Google Drive
        env:
          DVC_GOOGLE_TOKEN: ${{ secrets.DVC_GOOGLE_TOKEN }}
          DVC_GOOGLE_CLIENT_ID: ${{ secrets.DVC_GOOGLE_CLIENT_ID }}
          DVC_GOOGLE_CLIENT_SECRET: ${{ secrets.DVC_GOOGLE_CLIENT_SECRET }}
        run: |
          mkdir -p "$HOME/.cache/pydrive2fs/${DVC_GOOGLE_CLIENT_ID}"

          echo "$DVC_GOOGLE_TOKEN" | base64 -d \
            > "$HOME/.cache/pydrive2fs/${DVC_GOOGLE_CLIENT_ID}/default.json"

          chmod 600 \
            "$HOME/.cache/pydrive2fs/${DVC_GOOGLE_CLIENT_ID}/default.json"

          dvc remote modify --local gdrive gdrive_client_id "$DVC_GOOGLE_CLIENT_ID"

          dvc remote modify --local gdrive gdrive_client_secret "$DVC_GOOGLE_CLIENT_SECRET"

      # 5. Pull DVC data
      - name: Pull DVC Data
        run: |
          dvc pull -v

      # 6. Verify dataset
      - name: Verify Dataset
        run: |
          ls -lh data/raw/Loan_Default.csv

      # 7. Lint
      - name: Lint Code with Ruff
        run: |
          ruff check src/ tests/

      # 8. Run tests
      - name: Run Pytest
        run: |
          pytest tests/ -v

      # 9. Build Docker image
      - name: Build Docker Image
        run: |
          docker build \
            -t vikas61000/ml-eda-full-fledge:latest \
            -t vikas61000/ml-eda-full-fledge:${{ github.sha }} \
            .

      # 10. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 11. Push latest Docker image
      - name: Push Latest Docker Image
        run: |
          docker push vikas61000/ml-eda-full-fledge:latest

      # 12. Push versioned Docker image
      - name: Push Versioned Docker Image
        run: |
          docker push vikas61000/ml-eda-full-fledge:${{ github.sha }}